version: '3.8'

services:
    property-ads-finder:
        container_name: property-ads-finder
        build:
            context: .
            dockerfile: docker/Dockerfile
        image: ghcr.io/jagfx/property-ads-finder:latest
        restart: always
        volumes:
            -   .:/srv
        ports:
            - "4096:80"