name: Docker Image CI
on:
  create:
    tags:
      - v*
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Login to gitHub container registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.PAT }}

    - name: Build and push docker image
      run: |
        docker build . --file docker/Dockerfile --tag ghcr.io/jagfx/property-ads-finder:latest
        docker push ghcr.io/jagfx/property-ads-finder:latest
